Correct error handling in API controller
Summary:
Flask-Restful has broken behavior when propagating exceptions, and the current
release introduces other (broken) behavior so an upgrade is not possible.

This corrects the following error:

```
Traceback (most recent call last):
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/gevent/pywsgi.py", line 438, in handle_one_response
    self.run_application()
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/gevent/pywsgi.py", line 425, in run_application
    self.process_result()
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/gevent/pywsgi.py", line 414, in process_result
    for data in self.result:
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/raven/middleware.py", line 35, in __call__
    iterable = self.application(environ, start_response)
  File "/Users/cramer/Development/changes/changes/utils/trace.py", line 109, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/werkzeug/contrib/fixers.py", line 144, in __call__
    return self.app(environ, start_response)
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/flask_restful/__init__.py", line 250, in error_router
    return self.handle_error(e)
  File "/Users/cramer/Development/changes/changes/api/controller.py", line 6, in handle_error
    return super(APIController, self).handle_error(e)
  File "/Users/cramer/.virtualenvs/changes/lib/python2.7/site-packages/flask_restful/__init__.py", line 268, in handle_error
    raise exc
TypeError: __init__() takes at least 4 arguments (2 given)
```

Test Plan: This is testable by introducing an error in any endpoint, and hitting it via the webserver (**not** via unit tests, as they have different behavior).

Reviewers: cf

Reviewed By: cf

Differential Revision: https://tails.corp.dropbox.com/D35782